# Generated by Django 4.2.20 on 2025-10-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_account_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='fax',
            field=models.CharField(max_length=1000, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(max_length=1000, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc', verbose_name='identity image'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drives Licence'), ('international_passport', 'International Passport')], max_length=140, verbose_name='identity type'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40, verbose_name='marrital status'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=models.CharField(max_length=1000, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='kyc', verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
