# Generated by Django 4.2.20 on 2025-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('image', models.ImageField(upload_to='image home')),
                ('supported_currencies', models.PositiveIntegerField()),
                ('available_countries', models.PositiveIntegerField()),
                ('payment_methods', models.PositiveIntegerField()),
                ('support_team', models.PositiveIntegerField()),
                ('peace_of_mind', models.CharField(max_length=1000)),
                ('business_ready', models.CharField(max_length=1000)),
                ('transparent', models.CharField(max_length=1000)),
                ('international_network', models.CharField(max_length=1000)),
                ('payments', models.CharField(max_length=1000)),
                ('collections', models.CharField(max_length=1000)),
                ('conversions', models.CharField(max_length=1000)),
                ('global_account', models.CharField(max_length=1000)),
                ('register_for_free', models.CharField(max_length=1000)),
                ('set_up_your_transfer', models.CharField(max_length=1000)),
                ('make_your_payment', models.CharField(max_length=1000)),
                ('you_all_done', models.CharField(max_length=1000)),
                ('android_app', models.URLField(blank=True, max_length=500, null=True)),
                ('ios_app', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
