# Generated by Django 4.2.20 on 2025-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='support_team',
        ),
        migrations.AddField(
            model_name='home',
            name='support_team_day',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='home',
            name='support_team_hour',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
