# Generated by Django 4.2.20 on 2025-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_home_support_team_home_support_team_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweringFrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_money_online', models.CharField(max_length=1000)),
                ('money_transfer_fees', models.CharField(max_length=1000)),
                ('fast_send_money', models.CharField(max_length=1000)),
                ('use_app', models.CharField(max_length=1000)),
                ('protect_your_money', models.CharField(max_length=1000)),
                ('money_transfer_apps_safe', models.CharField(max_length=1000)),
                ('money_can_i_send', models.CharField(max_length=1000)),
                ('currency_can_i_send', models.CharField(max_length=1000)),
                ('Cancel_transaction', models.CharField(max_length=1000)),
                ('Can_i_send_multiple_payments', models.CharField(max_length=1000)),
            ],
        ),
    ]
