# Generated by Django 4.2.20 on 2025-10-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_answeringfrequentlyaskedquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='currency_can_i_send',
            new_name='are_money_transfer_apps_safe',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='fast_send_money',
            new_name='how_does_Paylio_protect_your_money',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='money_can_i_send',
            new_name='how_much_are_money_transfer_fees',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='money_transfer_apps_safe',
            new_name='how_much_money_can_i_send',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='money_transfer_fees',
            new_name='how_to_send_money_online',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='protect_your_money',
            new_name='how_to_use_app',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='send_money_online',
            new_name='what_is_the_fastest_way_to_send_money_abroad',
        ),
        migrations.RenameField(
            model_name='answeringfrequentlyaskedquestions',
            old_name='use_app',
            new_name='which_currency_can_i_send',
        ),
    ]
