# Generated by Django 4.2.20 on 2025-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_answeringfrequentlyaskedquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('logo', models.ImageField(upload_to='company_logos', verbose_name='logo')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('support_mail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Support Mail')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('android_app', models.URLField(blank=True, max_length=500, null=True)),
                ('ios_app', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='android_app',
        ),
        migrations.RemoveField(
            model_name='home',
            name='ios_app',
        ),
    ]
