# Generated by Django 4.2.20 on 2025-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_remove_home_android_app_remove_home_ios_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='android_app',
            field=models.URLField(blank=True, null=True, verbose_name='android app'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ios_app',
            field=models.URLField(blank=True, null=True, verbose_name='ios app'),
        ),
    ]
