# Generated by Django 4.2.20 on 2025-10-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_company_android_app_alter_company_ios_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Can_i_send_multiple_payments',
        ),
        migrations.RemoveField(
            model_name='home',
            name='Cancel_transaction',
        ),
        migrations.RemoveField(
            model_name='home',
            name='are_money_transfer_apps_safe',
        ),
        migrations.RemoveField(
            model_name='home',
            name='how_does_Paylio_protect_your_money',
        ),
        migrations.RemoveField(
            model_name='home',
            name='how_much_are_money_transfer_fees',
        ),
        migrations.RemoveField(
            model_name='home',
            name='how_much_money_can_i_send',
        ),
        migrations.RemoveField(
            model_name='home',
            name='how_to_send_money_online',
        ),
        migrations.RemoveField(
            model_name='home',
            name='how_to_use_app',
        ),
        migrations.RemoveField(
            model_name='home',
            name='what_is_the_fastest_way_to_send_money_abroad',
        ),
        migrations.RemoveField(
            model_name='home',
            name='which_currency_can_i_send',
        ),
        migrations.AddField(
            model_name='company',
            name='Can_i_send_multiple_payments',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='Cancel_transaction',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='are_money_transfer_apps_safe',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='how_does_Paylio_protect_your_money',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='how_much_are_money_transfer_fees',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='how_much_money_can_i_send',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='how_to_send_money_online',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='how_to_use_app',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='what_is_the_fastest_way_to_send_money_abroad',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='which_currency_can_i_send',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
