# Generated by Django 4.2.20 on 2025-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_home_can_i_send_multiple_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='video',
        ),
        migrations.AddField(
            model_name='company',
            name='see_how_it_Works',
            field=models.FileField(default=1, upload_to='videos', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='See How it Works'),
        ),
    ]
