# Generated by Django 4.2.20 on 2025-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_home_video_company_see_how_it_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='see_how_it_Works',
            field=models.FileField(upload_to='videos', verbose_name='See How it Works'),
        ),
    ]
