# Generated by Django 4.2.20 on 2025-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_company_address_alter_company_see_how_it_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_users',
            field=models.CharField(default=1, max_length=255, verbose_name='Active Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='countries_supported',
            field=models.CharField(default=1, max_length=255, verbose_name='Countries Supported'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='fast_processing',
            field=models.CharField(default=1, max_length=255, verbose_name='Fast Processing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='global_coverage',
            field=models.CharField(default=1, max_length=255, verbose_name='Global Coverage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='our_mission',
            field=models.CharField(default=1, max_length=255, verbose_name='Our Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='our_vision',
            field=models.CharField(default=1, max_length=255, verbose_name='Our Vision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='secure_payments',
            field=models.CharField(default=1, max_length=255, verbose_name='Secure Payments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='system_uptime',
            field=models.CharField(default=1, max_length=255, verbose_name='System Uptime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='transactions',
            field=models.CharField(default=1, max_length=255, verbose_name='Transactions'),
            preserve_default=False,
        ),
    ]
