# Generated by Django 4.2.20 on 2025-10-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_kyc'),
        ('core', '0014_company_active_users_company_countries_supported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Can_i_send_multiple_payments',
            field=models.CharField(max_length=1000, verbose_name='Can i send multiple payments'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Cancel_transaction',
            field=models.CharField(max_length=1000, verbose_name='Cancel transaction'),
        ),
        migrations.AlterField(
            model_name='company',
            name='are_money_transfer_apps_safe',
            field=models.CharField(max_length=1000, verbose_name='are money transfer apps safe'),
        ),
        migrations.AlterField(
            model_name='company',
            name='how_does_Paylio_protect_your_money',
            field=models.CharField(max_length=1000, verbose_name='how does Paylio protect your money'),
        ),
        migrations.AlterField(
            model_name='company',
            name='how_much_are_money_transfer_fees',
            field=models.CharField(max_length=1000, verbose_name='how much are money transfer fees'),
        ),
        migrations.AlterField(
            model_name='company',
            name='how_much_money_can_i_send',
            field=models.CharField(max_length=1000, verbose_name='how much money can i send'),
        ),
        migrations.AlterField(
            model_name='company',
            name='how_to_send_money_online',
            field=models.CharField(max_length=1000, verbose_name='how to send money online'),
        ),
        migrations.AlterField(
            model_name='company',
            name='how_to_use_app',
            field=models.CharField(max_length=1000, verbose_name='how_to_use_app'),
        ),
        migrations.AlterField(
            model_name='company',
            name='what_is_the_fastest_way_to_send_money_abroad',
            field=models.CharField(max_length=1000, verbose_name='what is the fastest way to send money abroad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='which_currency_can_i_send',
            field=models.CharField(max_length=1000, verbose_name='which currency can i send'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=20, prefix='CARD', unique=True, verbose_name='card id'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Visa', 'Visa'), ('Verve', 'Verve')], default='Master', max_length=20, verbose_name='card type'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.IntegerField(verbose_name='cvv'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.IntegerField(verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='home',
            name='available_countries',
            field=models.PositiveIntegerField(verbose_name='available countries'),
        ),
        migrations.AlterField(
            model_name='home',
            name='business_ready',
            field=models.CharField(max_length=1000, verbose_name='business ready'),
        ),
        migrations.AlterField(
            model_name='home',
            name='collections',
            field=models.CharField(max_length=1000, verbose_name='collections'),
        ),
        migrations.AlterField(
            model_name='home',
            name='conversions',
            field=models.CharField(max_length=1000, verbose_name='conversions'),
        ),
        migrations.AlterField(
            model_name='home',
            name='global_account',
            field=models.CharField(max_length=1000, verbose_name='global account'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='image home', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='international_network',
            field=models.CharField(max_length=1000, verbose_name='international network'),
        ),
        migrations.AlterField(
            model_name='home',
            name='make_your_payment',
            field=models.CharField(max_length=1000, verbose_name='make your payment'),
        ),
        migrations.AlterField(
            model_name='home',
            name='payment_methods',
            field=models.PositiveIntegerField(verbose_name='payment methods'),
        ),
        migrations.AlterField(
            model_name='home',
            name='payments',
            field=models.CharField(max_length=1000, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='home',
            name='peace_of_mind',
            field=models.CharField(max_length=1000, verbose_name='peace of mind'),
        ),
        migrations.AlterField(
            model_name='home',
            name='register_for_free',
            field=models.CharField(max_length=1000, verbose_name='register for free'),
        ),
        migrations.AlterField(
            model_name='home',
            name='set_up_your_transfer',
            field=models.CharField(max_length=1000, verbose_name='set up your transfer'),
        ),
        migrations.AlterField(
            model_name='home',
            name='support_team_day',
            field=models.PositiveIntegerField(default=7, verbose_name='support team day'),
        ),
        migrations.AlterField(
            model_name='home',
            name='support_team_hour',
            field=models.PositiveIntegerField(default=24, verbose_name='support team hour'),
        ),
        migrations.AlterField(
            model_name='home',
            name='supported_currencies',
            field=models.PositiveIntegerField(verbose_name='supported currencies'),
        ),
        migrations.AlterField(
            model_name='home',
            name='transparent',
            field=models.CharField(max_length=1000, verbose_name='transparent'),
        ),
        migrations.AlterField(
            model_name='home',
            name='you_all_done',
            field=models.CharField(max_length=1000, verbose_name='you all done'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='', verbose_name='nid'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Transfer', 'Transfer'), ('Credit Alert', 'Credit Alert'), ('Debit Alert', 'Debit Alert'), ('Sent Payment Request', 'Sent Payment Request'), ('Recieved Payment Request', 'Recieved Payment Request'), ('Funded Credit Card', 'Funded Credit Card'), ('Withdrew Credit Card Funds', 'Withdrew Credit Card Funds'), ('Deleted Credit Card', 'Deleted Credit Card'), ('Added Credit Card', 'Added Credit Card')], default='none', max_length=100, verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever', to=settings.AUTH_USER_MODEL, verbose_name='reciever'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever_account', to='account.account', verbose_name='reciever account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_account', to='account.account', verbose_name='sender account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending'), ('processing', 'Processing'), ('request_sent', 'Request Sent'), ('request_settled', 'Request Settled'), ('request_processing', 'Request Processing')], default='pending', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=20, prefix='TRN', unique=True, verbose_name='transaction id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Recieved', 'Recieved'), ('Withdraw', 'Withdraw'), ('Refund', 'Refund'), ('request', 'Payment Request'), ('none', 'None')], default='none', max_length=100, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
