# Generated by Django 5.2.7 on 2025-12-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
