# Generated by Django 5.2.7 on 2025-12-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_kyc_account_alter_kyc_city_alter_kyc_country_and_more'),
        ('core', '0021_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_notifications', to='account.account', verbose_name='user'),
        ),
    ]
