# Generated by Django 5.2.7 on 2026-01-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icons',
            field=models.ImageField(default=1, upload_to='company_icons', verbose_name='icons'),
            preserve_default=False,
        ),
    ]
